### ISSUE TITLE
Running e2e tests in Docker 

### ISSUE THREAD

**Issue by talexandru1987** [talexandru1987/DevOps-Course-Starter#8]
The e2e tests run successfully on my local machine. I get an error when I try to run the tests in the docker image. 

I built the image using:
docker build --target test --tag my-test-image .

I run the image using:
docker run --env-file .env my-test-image

The error I get is:
$ docker run --env-file .env my-test-image
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /app
collected 9 items

todo_app/tests/test_view_model.py .......                                [ 77%]
todo_app/tests_e2e/test_app_e2e.py EE                                    [100%]

==================================== ERRORS ====================================
_____________________ ERROR at setup of test_task_journey ______________________

>   ???

D:\DEVELOPMENT\DevOps-Course-Starter\todo_app\tests_e2e\conftest.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.10/os.py:685: in __setitem__
    value = self.encodevalue(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = False

    def encode(value):
        if not isinstance(value, str):
>           raise TypeError("str expected, not %s" % type(value).__name__)
E           TypeError: str expected, not bool

/usr/lib/python3.10/os.py:757: TypeError
---------------------------- Captured stdout setup -----------------------------
An error occured: 401 Client Error: Unauthorized for url: https://api.trello.com/1/boards/?key=this-is-a-fake-token&token=this-is-a-fake-token&name=testBoard
___________________ ERROR at setup of test_navigate_to_board ___________________

>   ???

D:\DEVELOPMENT\DevOps-Course-Starter\todo_app\tests_e2e\conftest.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.10/os.py:685: in __setitem__
    value = self.encodevalue(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = False

    def encode(value):
        if not isinstance(value, str):
>           raise TypeError("str expected, not %s" % type(value).__name__)
E           TypeError: str expected, not bool

/usr/lib/python3.10/os.py:757: TypeError
=========================== short test summary info ============================
ERROR todo_app/tests_e2e/test_app_e2e.py::test_task_journey - TypeError: str ...
ERROR todo_app/tests_e2e/test_app_e2e.py::test_navigate_to_board - TypeError:...
========================= 7 passed, 2 errors in 5.17s ==========================

For the CI pipeline run I use:
docker run -e TRELLO_TOKEN=${{ secrets.TOKEN }} -e TRELLO_KEY=${{ secrets.KEY }} test-image

**Comment by JackMeadDev** [comment]
Commenting to give myself a structure for the call:
One interesting error message is:
> An error occured: 401 Client Error: Unauthorized for url: https://api.trello.com/1/boards/?key=this-is-a-fake-token&token=this-is-a-fake-token&name=testBoard
Which suggests that your fake key/token are getting set in your container, and preventing the e2e test talking to Trello

The most likely reason is because:
* We're setting the real, secret, environment variables first directly
* Then we're running the unit & integration tests
  * Which load in the fake variables
* Then we're running the end-to-end tests
  * Which now use the fake variables!

So one simple approach might be to run the two sets of tests separately, by taking advantage of the fact we can specify a folder to pytest, and we can do that at runtime with arguments after the image name:
* `docker run test-image todo_app/tests`
* `docker run -e TRELLO_TOKEN=${{ secrets.TOKEN }} -e TRELLO_KEY=${{ secrets.KEY }} test-image todo_app/tests_e2e`

**Comment by JackMeadDev** [comment]
From conversation: `docker run --entrypoint poetry test-image run pytest todo_app/tests`
